const locations: Location[] = [
  {
    id: 1,
    city: "Paris",
    country: "France",
    lat: 48.8566,
    lng: 2.3522,
    agent: "Sophie Dubois",
    phone: "+33 6 65 45 51 65",
    label: "Hub d’innovation",
    timezone: "Europe/Paris",
  },
  {
    id: 2,
    city: "New York",
    country: "USA",
    lat: 40.7128,
    lng: -74.006,
    agent: "John Doe",
    phone: "+1 555 123 456",
    label: "Head Office",
    timezone: "America/New_York",
  },
  {
    id: 3,
    city: "London",
    country: "UK",
    lat: 51.5074,
    lng: -0.1278,
    agent: "James Wilson",
    phone: "+44 20 7123 4567",
    label: "Financial Tech Hub",
    timezone: "Europe/London",
  },
  {
    id: 4,
    city: "Berlin",
    country: "Germany",
    lat: 52.52,
    lng: 13.405,
    agent: "Klaus Muller",
    phone: "+49 30 12345678",
    label: "Tech Innovation",
    timezone: "Europe/Berlin",
  },
  {
    id: 5,
    city: "Amsterdam",
    country: "Netherlands",
    lat: 51.5074,
    lng: -0.1278,
    agent: "Emma Van Berg",
    phone: "+31 20 1234567",
    label: "Digital Solutions Hub",
    timezone: "Europe/Amsterdam",
  },
];

interface Location {
  id: number,
  city: string,
  country: string,
  lat: number,
  lng: number,
  agent: string,
  phone: string,
  label: string,
  timezone: string,
}

export default locations;
